services:
  app:
    build: .
    container_name: uni-event-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7
    container_name: uni-event-redis
    ports:
      - "6379:6379"
